name: Deploy docs to Github Pages
on:
  workflow_dispatch:
  release:
    type: [published]
    branches:
      - dev
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: pnpm install --frozen-lockfile
      - run: tsc
      - run: touch ./docs/.nojekyll
      - run: |
          cd ./playground
          pnpm install --frozen-lockfile
          pnpm build
          pnpm export -o ../docs
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: .
