name: Deploy docs to Github Pages
on:
  workflow_dispatch:
  release:
    type: [published]
    branches:
      - main
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "22.13.0"
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/checkout@v4
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: |
          node -v
          pnpm -v
      - run: |
          cd ./playground
          pnpm install --frozen-lockfile
          pnpm build
          pnpm export
          touch ../docs/.nojekyll
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: .
